#!/bin/bash

## Create a new repository on the command line

echo "# myrepo" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/username/reponame.git
git push -u origin master


### Pushing an existing repository from the command line


git remote add origin https://github.com/username/reponame.git
git pull origin master --allow-unrelated-histories
git commit -a -m "merge"
git push -u origin master

