# Specifies the official PHP image with Apache pre-installed for version 7.4.
FROM php:7.4-apache 
# Sets the working directory to the Apache document root
WORKDIR  /var/www/html
# Copies your index.php file from the build context to the document root inside the container.
COPY index.php /var/www/html
# Copies the connection.php file to the document root.
COPY conection.php /var/www/html
# Installs the required development libraries for the GD extension:
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \ 
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli

# Exposes port 80, which is the default port for Apache web traffic.
EXPOSE 80
