#!/bin/bash


echo  "Creating directories..."
echo ____________________________________________________

sudo mkdir /public
echo "Directorio `publico` criado"
sudo mkdir /adm
echo "Directorio `adm` criado"
sudo mkdir /ven
echo "Directorio `ven` criado"
sudo mkdir /sec
echo "Directorio `sec` criado"

echo ____________________________________________________

echo "Criando grupos de usuarios..."

echo ____________________________________________________

sudo groupadd GRP_ADM
echo "Grupo ADM adicionado"
sudo groupadd GRP_VEN
echo "Grupo VEN adicionado"
sudo groupadd GRP_SEC
echo "Grupo SEC adicionado"

echo ____________________________________________________

echo "Criando usuarios..."

sudo useradd carlos -m -s /bin/bash -G GRP_ADM
echo "Usuario carlos criado"
sudo useradd maria  -m -s /bin/bash -G GRP_ADM
echo "Usuario maria criado"
sudo useradd joao   -m -s /bin/bash -G GRP_ADM
echo "Usuario joao criado"

echo ____________________________________________________

sudo useradd debora -m -s /bin/bash -G GRP_VEN
echo "Usuario debora adicionada a grupo vendas"
sudo useradd sebastiana -m -s /bin/bash -G GRP_VEN
echo "Usuario sebastiana adicionada a grupo vendas"
sudo useradd roberto -m -s /bin/bash -G GRP_VEN
echo "Usuario roberto adicionado a grupo vendas"

echo ____________________________________________________

sudo useradd josefina -m -s /bin/bash -G GRP_SEC
echo "Usuario josefina adicionado a grupo secretaria"
sudo useradd amanda  -m -s /bin/bash -G GRP_SEC
echo "Usuario amanda adicionado a grupo secretaria"
sudo useradd rogerio -m -s /bin/bash -G GRP_SEC
echo "Usuario rogerio adicionado a grupo secretaria"

echo ____________________________________________________

echo " Especificando permissoes dos diretorios..."

sudo chown root:GRP_ADM /adm
echo "Usuario root adicionado como administrador do grupo ADM"
sudo chown root:GRP_VEN /ven
echo "Usuario root adicionado como administrador do grupo VEN"
sudo chown root:GRP_SEC /sec
echo "Usuario root adicionado como administrador do grupo SEC"

echo ____________________________________________________

sudo chmod 770 /adm
echo "Leitura, escritura e execucao adicionadas para dono e grupo ADM"
sudo chmod 770 /ven
echo "Leitura, escritura e execucao adicionadas para dono e grupo VEN"
sudo chmod 770 /sec
echo "Leitura, escritura e execucao adicionadas para dono e grupo SEC"
sudo chmod 777 /publico
echo "Leitura, escritura e execucao adicionadas para dono,grupo publico"

echo ____________________________________________________

echo "Fim do script..."



